### ISSUE TITLE
Bad link of /app/btsync and btsync cannot start.

### ISSUE THREAD

**Issue by beeblebrox** [linuxserver/docker-btsync#1]
In init/50_check_for_config.sh shouldn't the lines stating:

```
ln -s /app/btsync /app/btsync-latest
ln -s /app/btsync /app/btsync-1.4
```

have the source and target reversed?  When I run the container it fails on the link stating target already exists (because it does) and won't start: `setuser: cannot execute /app/btsync: [Errno 2] No such file or directory`

As a side note, (because I do not know where to ask) I enjoy your containers and was wondering if you have plans on creating a dropbox container?

**Comment by sparklyballs** [comment]
reference #2
