### ISSUE TITLE
image linuxserver/btsync:latest not found

### ISSUE THREAD

**Issue by tommy31** [linuxserver/docker-btsync#5]
Hi, 
I tried to build this image but i got this error. Look like the docker image does not appear in docker hub.

```Unable to find image 'linuxserver/btsync:latest' locally
Pulling repository docker.io/linuxserver/btsync
Error: image linuxserver/btsync:latest not found```

**Comment by tobbenb** [comment]
Sorry, we forgot to delete the repo. Btsync is replaced by resilio.
